name: production

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    if: github.event.base_ref=='refs/heads/master'  # check the branch, if it's not master, skip the job.
    name: Deploy Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16.6.2'
          check-latest: true

      - name: Setup Env
        run: |
          cp .env.pipeline .env.local

      - name: Install NPM Dependencies
        run: |
          npm install

      - name: Build App
        run: npm run build

      - name: Run tests with Jest
        run: npm test
